### ISSUE TITLE
Outputting all interpolated meteorological input variables

### ISSUE THREAD

**Issue by ttf-g** [openamundsen/openamundsen#105]
The question is basically if openAMUNDSEN can also be used as a 'interpolation machinery' in order to obtain interpolated grids of the input variables. 
I have several input meteorological point measurements and would like to obtain the interpolated grids for the following variables (which are present in the input data):   

- Incident shortwave radiation (W m-2)
- Incident longwave radiation ( W m-2)
- Precipitation (Kg-2 m-2 s-1)
- Temperature (K)
- Relative Humidity (%)
- Wind speed (m s-1)
- Atmospheric pressure (Pa)

In the default settings of the configuration YAML file only temperature and precipitation are defined as gridded outputs. Is it possible to output also the rest of the variables?  I couldn't find any information about the internal variable names for the variables indicated above. In the following you can find the respective part of the YAML configuration file (obviously with wrong variable names).  

```
output_data:
  grids:
    format: netcdf
    variables:
   # Temperature (hourly mean)
      - var: meteo.temp # internal variable name
        name: temp_hourly # NetCDF output variable name
        freq: H # write frequency (if not specified, write every timestep)
        agg: mean # aggregation function ("sum", "mean" or empty)

    # Precipitation (hourly sum)
      - var: meteo.precip # internal variable name
        name: precip_hourly # NetCDF output variable name
        freq: H # write frequency (if not specified, write every timestep)
        agg: sum  # aggregation function ("sum", "mean" or empty)

    # Wind spped (hourly mean)
      - var: meteo.wind_speed # internal variable name
        name: wind_speed_hourly # NetCDF output variable name
        freq: H # write frequency (if not specified, write every timestep)
        agg: mean  # aggregation function ("sum", "mean" or empty)

    # Relative humidity (hourly mean)
      - var: meteo.relative_humidity # internal variable name
        name: humidity_hourly # NetCDF output variable name
        freq: H # write frequency (if not specified, write every timestep)
        agg: mean  # aggregation function ("sum", "mean" or empty)

    # Atmospheric pressure (hourly mean)
      - var: meteo.atmospheric_pressure # internal variable name
        name: atmos_pressure_hourly # NetCDF output variable name
        freq: H # write frequency (if not specified, write every timestep)
        agg: mean  # aggregation function ("sum", "mean" or empty)

    # Long wave radiation in (hourly mean)
      - var: meteo.lw_in # internal variable name
        name: lw_in_hourly # NetCDF output variable name
        freq: H # write frequency (if not specified, write every timestep)
        agg: mean  # aggregation function ("sum", "mean" or empty)

    # Short wave radiation in (hourly mean)
      - var: meteo.sw_in # internal variable name
        name: sw_in_hourly # NetCDF output variable name
        freq: H # write frequency (if not specified, write every timestep)
        agg: mean  # aggregation function ("sum", "mean" or empty)
```
