### ISSUE TITLE
Change filenames for aggregated grid outputs when using ASCII output

### ISSUE THREAD

**Issue by fhanzer** [openamundsen/openamundsen#33]
e.g.

```yaml
- var: meteo.precip
  freq: A
  agg: sum
```

results in file named `precip_1997-12-31T2300.asc`, probably better use e.g. `precip_sum_1997-01-01T0000_1997-12-31T2300.asc`
