### ISSUE TITLE
Output File Issue

### ISSUE THREAD

**Issue by 5P3C7ER** [openamundsen/openamundsen#82]
I want output in **.gif or .tiff** format. 
Anyone can help me to get the output in the format.

I am using Jupiter in anaconda software.

**Comment by fhanzer** [comment]
Hi! You can output data in GeoTIFF format by setting the grid output format configuration key to `geotiff`. Like this in the YAML file:

```yaml
output_data:
  grids:
    format: geotiff
```
